### ISSUE TITLE
Trained network file not getting saved in Linux

### ISSUE THREAD

**Issue by zz4032** [nodchip/Stockfish#10]
No files are being created after training phase.
```
$./stockfish-nnue-learn-use-blas
Stockfish 220620 64 BMI2 by T. Romstad, M. Costalba, J. Kiiski, G. Linscott
setoption name SkipLoadingEval value true
setoption name Threads value 6
setoption name EvalSaveDir value evalsave
isready
readyok
learn targetdir trainingdata loop 100 batchsize 1000000 eta 1.0 lambda 0.5 eval_limit 32000 nn_batch_size 1000 newbob_decay 0.5 eval_save_interval 10000000 loss_output_interval 1000000 mirror_percentage 50 validation_set_file_name validationdata/generated_kifu.bin
[...]
finalize..all threads are joined.
Check Sum = 0
save_eval() start. folder = evalsave/final
save_eval() finished. folder = evalsave/final
quit
```
Correct folder structure exists:
```
./trainingdata/generated_kifu.bin
./validationdata/generated_kifu.bin
./evalsave
```
Also tried 
`setoption name EvalSaveDir value .`
`setoption name EvalSaveDir value ./evalsave`
`setoption name EvalSaveDir value evalsave/nn.bin`
`setoption name EvalSaveDir value /complete/path/evalsave`
and training with executable`stockfish-nnue-learn` (without blas).

The same commands with copied folder structure and files on a Windows system worked fine and a network file was created as expected in folder evalsave.

Linux build was compiled with bmi2 architecture and `c++14` replaced with `c++17` and `LDFLAGS += -static` commented out on two occasions in Makefile.

**Comment by nodchip** [comment]
I'm sorry but I don't have any environments to reproduce the steps.  Could you please some to investigate, and fix it?  Pull requests are always welcome.

**Comment by lp200** [comment]
Maybe creating  ./evalsave/final folder will solve the problem.

**Comment by zz4032** [comment]
Indeed I had to create all folders myself. Function for creating directories was not called on Linux (corrected with PR).
