### ISSUE TITLE
Modern (popcount) compiles for Ryzen CPUs

### ISSUE THREAD

**Issue by joergoster** [nodchip/Stockfish#11]
where BMI2 instructions are still rather slow.

2 changes were needed to allow compiling under msys2 with `make nnue ARCH=x86-64-modern COMP=mingw `

1. Include 2 missing headers, see https://github.com/joergoster/Stockfish-NNUE/commit/f1426d03556618c710a7d6402f12e581e329dcdd (Kudos to @adtreat!)
2. Add -mavx2 switch to the popcount section in Makefile, see https://github.com/joergoster/Stockfish-NNUE/commit/411ee5b39ccfa25064af60e5371f458632e7ee8a

**Comment by nodchip** [comment]
I released a new binary set.
https://github.com/nodchip/Stockfish/releases/tag/stockfish-nnue-2020-06-24

Please try it.

**Comment by joergoster** [comment]
@nodchip Thank you!

I'm trying to get rid of all the warnings during compilation.
In Position::set() in position.cpp, we initialize a Position object from a given FEN. Since you added 2 new members to the StateInfo struct in position.h, the `std::memset(si, 0, sizeof(StateInfo));` of the StateInfo object `si` issues a warning. Is it safe to simply skip this zero-initialization step for the two new members `Eval::NNUE::Accumulator accumulator;` and `Eval::DirtyPiece dirtyPiece;`?

**Comment by nodchip** [comment]
You're welocme.

I think that is it not related to the original topic in this issue.  Could you please create another issue?
