### ISSUE TITLE
Potential null PackedSfenValue entries in gensfen output.

### ISSUE THREAD

**Issue by Sopel97** [nodchip/Stockfish#112]
I have received one big .bin file (~125M entries) with about 80 entries (~uniformly distributed) being just null bytes. Such entries crash learning. Initially I thought that this might be a shuffle issue, but since it is not present in any other shuffled files it is most likely somehow coming from gensfen. I've been looking for a potential source of this but the only place where such entries arise is https://github.com/nodchip/Stockfish/blob/master/src/learn/gensfen.cpp#L933 and they are filled in functions that cannot fail. Since the file was shuffled I have no way of knowing if these entries were consecutive or happened spuriously. I'm debating a temporary defensive solution that would involve removing null entries just before writing to disk. If anyone has any idea how these could arise it would be great.

**Comment by vondele** [comment]
There are no null moves in this 200M list:
```
uci
setoption name Use NNUE value false
setoption name Threads value 30
setoption name Hash value 32768
setoption name SyzygyPath value /home/vondele/chess/syzygy/3-4-5
isready
gensfen depth 6 loop 200000000 use_draw_in_training_data_generation 1 eval_limit 32000 output_file_name gensfen_real.bin
learn gensfen_real.bin convert_plain output_file_name gensfen_real.txt
quit
```
so probably comes from some less standard.

**Comment by vondele** [comment]
Also no null moves in
```
uci
setoption name Use NNUE value false
setoption name Threads value 30
setoption name Hash value 32768
setoption name SyzygyPath value /home/vondele/chess/syzygy/3-4-5
isready
gensfen random_move_count 20 depth 3 loop 20000000 use_draw_in_training_data_generation 1 eval_limit 32000 output_file_name gensfen_real.bin
learn gensfen_real.bin convert_plain output_file_name gensfen_real.txt
quit
```

**Comment by vondele** [comment]
What I did seem to observe, are the files removed/truncated upon opening for writing? I didn't see that shrink in size, so that could mean people have corrupted data around?

**Comment by Sopel97** [comment]
The behaviour was always to append.

**Comment by vondele** [comment]
I'm converting all to .txt file and look for null moves, but there are no such moves as far as I can see. So, until there is a reproducer based on a sequence of commands executed on master, I will not worry.
