### ISSUE TITLE
Crash when no net can be loaded but SkipLoadingEval=false.

### ISSUE THREAD

**Issue by NightlyKing** [nodchip/Stockfish#113]
While trying to reproduce a certain crash it happened more than once that I forgot to set SkipLoadingEval=true. I think the correct way of dealing with this is to report an error and gracefully exit instead of just closing and confusing the user.

**Comment by nodchip** [comment]
I agree.  Pull requests are welcome.

**Comment by Sopel97** [comment]
IMO considering how spread the use of use_raw_nnue_eval is it would be best to go cfish way - a 3 state Use NNUE. That's a matter for a different PR though

**Comment by Sopel97** [comment]
This is no longer an issue. If `gensfen` or `learn` is called without a net loaded it outputs:
```
info string ERROR: If the UCI option "Use NNUE" is set to true, network evaluati
on parameters compatible with the engine must be available.
info string ERROR: The option is set to true, but the network file nn-c3ca321c51
c9.nnue was not loaded successfully.
info string ERROR: The UCI option EvalFile might need to specify the full path,
including the directory name, to the network file.
info string ERROR: The default net can be downloaded from: https://tests.stockfi
shchess.org/api/nn/nn-c3ca321c51c9.nnue
info string ERROR: The engine will be terminated now.
```
