### ISSUE TITLE
No debugging symbols with debug=yes

### ISSUE THREAD

**Issue by Sopel97** [nodchip/Stockfish#115]
https://github.com/nodchip/Stockfish/blob/master/src/Makefile#L43 `-s` is passed to the linker and it overrides `-g`. This option should only be present when `debug=no`

**Comment by vondele** [comment]
It probably should never be present... but maybe there is a use case for it.

**Comment by nodchip** [comment]
I added `-s` to reduce the size of released binaries.  #115 looks reasonable for me.
