### ISSUE TITLE
HalfKP-KK等が正しく動作しない

### ISSUE THREAD

**Issue by tttak** [nodchip/Stockfish#122]
こんばんは。日本語ですいません。

先日official-stockfishの方で[Remove EvalList](https://github.com/official-stockfish/Stockfish/commit/9b4967071e2fb116673820127522bc43d01d2257)がありましたが、
以前作成した色々なfeatureをこれに対応させようとしております。

PPは少し難しそうでしたので後回しにして、それ以外は概ねfeatureのコードとしては書けたと思っていました。
https://github.com/tttak/Stockfish/commits/features_20200830

```test nnue test_features```はすべてのfeatureでパスしたのですが、
改修前後でevalコマンドの結果を比べると、いくつかのarchitectureで結果が一致しませんでした。

具体的には、HalfKPE4、HalfKP_PieceCountのようにHalfKPを細分化した単一FeatureSetの場合はOKなのですが、
HalfKP-KK、HalfKP-Mobility-Pawnのような複合FeatureSetの場合がNGでした。

色々調べてみますと、NNUEがofficial-stockfishにマージされた際に
HalfKPを念頭において、それに不必要なコードの一部が削除されてしまったようです。

例えば、nnue_feature_transformer.hでkRefreshTriggersが複数の場合のコードが削除されてしまっておりました。
それを一部復元したのが https://github.com/tttak/Stockfish/commit/49350b3dcb1169236e2fb4803f1c65803bdf0d1f です。
（以前作成した色々なfeatureはofficial-stockfishにマージ前のコードを元にしていたため、期待どおりに動作していました）

ですので、このrepositoryにあるk-p_256x2-32-32.hやhalfkp-cr-ep_256x2-32-32.hも、おそらく正しく動作しなくなってしまっているように思われます。

上記の複数kRefreshTriggersのコードを元に戻してみましたが、それだけでは足りないようで、evalコマンドの結果がまだ一致しておりません。
これと似たような件で、何か思い当たる箇所等ございましたらご教示頂ければ幸いです。
（自分でコードを調べればいいのですが、もし何かヒントを頂ければと思い、質問させて頂きました次第です）

**Comment by nodchip** [comment]
お世話になっております。

k-p_256x2-32-32.hにつきましては、本家やねうら王のほうで `test nnue test_features` が失敗していたように記憶しています。そちらのほうについて確認してみるのはいかがでしょうか？

halfkp-cr-ep_256x2-32-32.hのほうについては、残念ながら何も思いつきませんでした。申し訳ありません。

**Comment by tttak** [comment]
早速ご返信頂きましてありがとうございます。
nnue_feature_transformer.hでkRefreshTriggersが複数の場合のコードをあと数か所revertしましたら、evalコマンドの結果が一致するようになりました。（ https://github.com/tttak/Stockfish/commit/c8116824d34df8f3b562e1ab7dff0825b5713f4a ）
お騒がせいたしました。

**Comment by nodchip** [comment]
問題が解決したようで何よりです。今後ご相談されたい内容等あれば、お気軽にお声がけください。
