### ISSUE TITLE
Re-introduce GlobalOptions and move global variables into it

### ISSUE THREAD

**Issue by nodchip** [nodchip/Stockfish#124]
YaneuraOu has GlobalOptions which contains options applied to wide area of code base.
https://github.com/yaneurao/YaneuraOu/blob/master/source/config.h#L393
It was partially ported to Stockfish NNUE.  But it was not used.  We could re-introduce GlobalOptions, and move global variables into it.

I'm not sure if this is a good idea or not.  Any comments are welcome.

**Comment by Sopel97** [comment]
In my opinion such global options should be handled by UCI.

**Comment by vondele** [comment]
I think so as well.

**Comment by nodchip** [comment]
I agree with @Sopel97 and @vondele .  We might experiment disabling transposition table on training.  We could add a UCI option to enable/disable transposition table then.
