### ISSUE TITLE
Assertion fail on reading Option "EvalDir"

### ISSUE THREAD

**Issue by Sopel97** [nodchip/Stockfish#128]
There's no option "EvalDir". It's read near the end of learner.cpp and casted to std::string. ucioption doesn't know this option -> doesn't know it's string -> fails assertion in Option::operator std::string.

**Comment by Sopel97** [comment]
at least that's what I'm suspecting. Does happen after gensfen too though. (with debug=yes of course). Can't debug now.

**Comment by nodchip** [comment]
I agree with you.  Pull requests from other developers are welcome.

**Comment by vondele** [comment]
I'm looking at this, I think the option is just not needed anymore. So, I'll prepare a patch with that assumption.
