### ISSUE TITLE
Decoupling gensfen/learn/conver declarations.

### ISSUE THREAD

**Issue by Sopel97** [nodchip/Stockfish#132]
I want to look tomorrow, among other things, into splitting learn.h and also remove locally made declarations for various stuff (like Learner namespace in uci.cpp). Now the last issue is the `use_raw_nnue_eval` option that's used for gensfen and learn is in an ugly state of being a global flag that can only be set through two commands. What is the consensus on the way we should handle `use_raw_nnue_eval`? I think we already decided that for global switches UCI options are the best, now should this be done as it's done in cfish (3 state Use NUUE) or should there be a dedicated option that takes higher priority over Use NNUE?

**Comment by nodchip** [comment]
+1 for UCI option with 3 state `Use NUUE`.
