### ISSUE TITLE
Naming inherited from shogi. Unification of nomenclature.

### ISSUE THREAD

**Issue by Sopel97** [nodchip/Stockfish#133]
The most common term that irks me is "sfen" that, I presume, means "Shogi FEN", which doesn't make sense not only in chess circles, but also in the way it's commonly used to describe a training data entry. (Even something as mindless as Training Data Entry (TDE) would be less confusing in my opinion.)

I've also seen a few comments in the code that refer to UCI as USI.

Should we try pursuing changing names that currently have no relation with ones used in chess? Looking at this from future perspective it would be weird if the only reason why something is named as it is would be that "it originated from shogi".

What other names in the codebase are currently borrowed? What could they be renamed to?

**Comment by nodchip** [comment]
I agree to try changing names with ones used in chess.  We could maintain the backward compatibility for commands and options for a while, and remove the compatibility at some point.
