### ISSUE TITLE
Weird research in gensfen?

### ISSUE THREAD

**Issue by Sopel97** [nodchip/Stockfish#149]
https://github.com/nodchip/Stockfish/blob/master/src/learn/gensfen.cpp#L896-L900 What is the purpose of this? Could it be replaced by clamping `search_depth_min` to 1?

**Comment by nodchip** [comment]
I'm not sure.  It was written in the YaneuraOu, and I ported as-is.  How about to ask in the YaneuraOu issues.  https://github.com/yaneurao/YaneuraOu/issues

**Comment by Sopel97** [comment]
https://github.com/yaneurao/YaneuraOu/issues/121#issuecomment-694055099 Looks like it could be removed

**Comment by nodchip** [comment]
I agree with you.

We are fixing regression between 2020-07-19 and 2020-08-30.  It is a bit danger to change gensfen code in this timing.  Could we remove it after the regression is fixed?

**Comment by Sopel97** [comment]
yes, I think that's wise
