### ISSUE TITLE
Regression between stockfish-nnue-2020-07-19 and stockfish-nnue-2020-08-30

### ISSUE THREAD

**Issue by nodchip** [nodchip/Stockfish#151]
In https://github.com/nodchip/Stockfish/issues/141, we found that there are regressions between stockfish-nnue-2020-07-19 and stockfish-nnue-2020-08-30.  We will investigate them.

**Comment by nodchip** [comment]
noobpwnftw said that this issue was fixed in master.
https://discordapp.com/channels/435943710472011776/737073080081317948/755006339658547211

I will also check it in https://github.com/nodchip/Stockfish/tree/get_shallow_value-2020-09-14.

**Comment by nodchip** [comment]
linox reported that the regression between stockfish-nnue-2020-07-19 and stockfish-nnue-2020-08-30 was that Eval::evaluate() does not return raw NNUE eval values.
https://discordapp.com/channels/435943710472011776/737073080081317948/755702418221826078
This was already fixed in https://github.com/nodchip/Stockfish/commit/c6f5f6a082592a2402f14908224fd33f9ad6fc0e.

I will investigate the regression between stockfish-nnue-2020-08-11 and stockfish-nnue-2020-08-30.

**Comment by nodchip** [comment]
To investigate this issue.  I planned to train nets with several commits between stockfish-nnue-2020-08-11 and stockfish-nnue-2020-08-30, and compare the Elos with stockfish-nnue-2020-07-19 vs stockfish-nnue-2020-08-11 and stockfish-nnue-2020-07-19 vs stockfish-nnue-2020-08-30.

The training data are same as #141.  They were created with https://github.com/nodchip/Stockfish/commit/bcfe28b2ae468d045e2f96b659401422531bacba and the following command.
```
uci
setoption name Use NNUE value false
setoption name Threads value 27
setoption name Hash value 32768
setoption name SyzygyPath value D:\data\chess\tablebase\3-4-5
isready
gensfen depth 6 loop 100000000 use_draw_in_training_data_generation 1 eval_limit 32000 output_file_name F:\stockfish\training_data\2020-09-12\Threads=27.Hash=32768.depth=6.loop=100000000.use_draw_in_training_data_generation=1.eval_limit=32000.bin
quit
``` 

The validation data are also same as #141.  They were created with https://github.com/nodchip/Stockfish/commit/bcfe28b2ae468d045e2f96b659401422531bacba and the following commands.
```
uci
setoption name Use NNUE value false
setoption name Threads value 27
setoption name Hash value 32768
setoption name SyzygyPath value D:\data\chess\tablebase\3-4-5
isready
gensfen depth 6 loop 1000000 use_draw_in_training_data_generation 1 eval_limit 32000 output_file_name F:\stockfish\validation_data\2020-09-12\generated_kifu.bin
quit
```

The reference net files were created with stockfish-nnue-2020-08-11 and stockfish-nnue-2020-08-30.  2020-08-11 was created with https://github.com/nodchip/Stockfish/commit/36092b855a5e2bcfb587a36e2055ea068e4bd8e5 and the following command.
``` 
uci
setoption name SkipLoadingEval value true
setoption name Threads value 16
setoption name EvalSaveDir value F:\stockfish\eval\2020-07-19.36092b855a5e2bcfb587a36e2055ea068e4bd8e5
isready
learn targetdir F:\stockfish\training_data\2020-09-12 loop 100 batchsize 1000000 use_draw_in_training 1 use_draw_in_validation 1 eta 1 lambda 1 eval_limit 32000 nn_batch_size 1000 newbob_decay 0.5 eval_save_interval 100000000 loss_output_interval 1000000 mirror_percentage 0 validation_set_file_name F:\stockfish\validation_data\2020-09-12\generated_kifu.bin
quit
```

2020-08-30 was created with https://github.com/nodchip/Stockfish/commit/35f04aaf24d05ec7b71c2cc1710d00642aaf35ec and the following command.
```
uci
setoption name SkipLoadingEval value true
setoption name Use NNUE value true
setoption name Threads value 16
setoption name EvalSaveDir value F:\stockfish\eval\2020-08-11.35f04aaf24d05ec7b71c2cc1710d00642aaf35ec
isready
learn targetdir F:\stockfish\training_data\2020-09-12 loop 100 batchsize 1000000 use_draw_in_training 1 use_draw_in_validation 1 eta 1 lambda 1 eval_limit 32000 nn_batch_size 1000 newbob_decay 0.5 eval_save_interval 100000000 loss_output_interval 1000000 mirror_percentage 0 validation_set_file_name F:\stockfish\validation_data\2020-09-12\generated_kifu.bin
quit
```

To detect the commit which introduced regression, I decided to binary search the commits.  The first target is https://github.com/nodchip/Stockfish/commit/17d2b5bf1747e2be281866bf1e623b3bb3a4a99f.  I created a net with the commit and the following command.
```
uci
setoption name SkipLoadingEval value true
setoption name Use NNUE value true
setoption name Threads value 16
setoption name EvalSaveDir value F:\stockfish\eval\2020-08-21.17d2b5b
isready
learn targetdir F:\stockfish\training_data\2020-09-12 loop 100 batchsize 1000000 use_draw_in_training 1 use_draw_in_validation 1 eta 1 lambda 1 eval_limit 32000 nn_batch_size 1000 newbob_decay 0.5 eval_save_interval 100000000 loss_output_interval 1000000 mirror_percentage 0 validation_set_file_name F:\stockfish\validation_data\2020-09-12\generated_kifu.bin
quit
```

The result of the training is below.

![image 2020-09-17-10-44-42](https://user-images.githubusercontent.com/685625/93411650-941f7200-f8d6-11ea-9734-341b0e682d12.png)

I uploaded the net to fishtest, and submitted a test (https://tests.stockfishchess.org/tests/view/5f62bac8912c15f19854b88e).  I will wait for the test result.

**Comment by nodchip** [comment]
https://github.com/nodchip/Stockfish/commit/35f04aaf24d05ec7b71c2cc1710d00642aaf35ec (2020-08-11) vs https://github.com/nodchip/Stockfish/commit/36092b855a5e2bcfb587a36e2055ea068e4bd8e5 (2020-07-19)
https://tests.stockfishchess.org/tests/view/5f5e0d2861bdd7a0007e76fa
ELO: -6.79 +-1.7 (95%) LOS: 0.0%
Total: 60000 W: 11291 L: 12464 D: 36245
Ptnml(0-2): 1254, 7452, 13560, 6681, 1053

https://github.com/nodchip/Stockfish/commit/17d2b5bf1747e2be281866bf1e623b3bb3a4a99f (2020-08-21) vs https://github.com/nodchip/Stockfish/commit/36092b855a5e2bcfb587a36e2055ea068e4bd8e5 (2020-07-19)
ELO: -20.66 +-1.7 (95%) LOS: 0.0%
Total: 60000 W: 9809 L: 13373 D: 36818
Ptnml(0-2): 1469, 8147, 13658, 5931, 795

https://github.com/nodchip/Stockfish/commit/bc90567e0933a49f8c1911eba45ec6743a37c1ec (2020-08-30) vs https://github.com/nodchip/Stockfish/commit/36092b855a5e2bcfb587a36e2055ea068e4bd8e5 (2020-07-19)
https://tests.stockfishchess.org/tests/view/5f5e0d7e61bdd7a0007e76fc
ELO: -28.50 +-1.8 (95%) LOS: 0.0%
Total: 60000 W: 9834 L: 14744 D: 35422
Ptnml(0-2): 1718, 8785, 12979, 5725, 793

The regression between https://github.com/nodchip/Stockfish/commit/36092b855a5e2bcfb587a36e2055ea068e4bd8e5 (2020-07-19) and https://github.com/nodchip/Stockfish/commit/35f04aaf24d05ec7b71c2cc1710d00642aaf35ec (2020-08-11) was `Use NNUE` = `pure`.  This was already fixed in master.

The still exists regression between https://github.com/nodchip/Stockfish/commit/35f04aaf24d05ec7b71c2cc1710d00642aaf35ec (2020-08-11) and https://github.com/nodchip/Stockfish/commit/17d2b5bf1747e2be281866bf1e623b3bb3a4a99f (2020-08-21).  We should investigate it.

There is another regression between https://github.com/nodchip/Stockfish/commit/17d2b5bf1747e2be281866bf1e623b3bb3a4a99f (2020-08-21) and https://github.com/nodchip/Stockfish/commit/bc90567e0933a49f8c1911eba45ec6743a37c1ec (2020-08-30).  We also need to investigate it.

**Comment by nodchip** [comment]
The second target is https://github.com/nodchip/Stockfish/commit/26460805437761cbef758bbfa9cc1fd1fbc6b6ef (2020-08-15).  I trained a net with the following command.
```
uci
setoption name SkipLoadingEval value true
setoption name Use NNUE value true
setoption name Threads value 16
setoption name EvalSaveDir value F:\stockfish\eval\2020-08-15.2646080
isready
learn targetdir F:\stockfish\training_data\2020-09-12 loop 100 batchsize 1000000 use_draw_in_training 1 use_draw_in_validation 1 eta 1 lambda 1 eval_limit 32000 nn_batch_size 1000 newbob_decay 0.5 eval_save_interval 100000000 loss_output_interval 1000000 mirror_percentage 0 validation_set_file_name F:\stockfish\validation_data\2020-09-12\generated_kifu.bin
quit
```

The training result is below.
![image 2020-09-18-10-08-40](https://user-images.githubusercontent.com/685625/93545153-b37fd300-f99a-11ea-92bd-530fa2f6bbe1.png)

I submitted a test to fishtest.  https://tests.stockfishchess.org/tests/view/5f640df7bb0cae038ca8f4c9

**Comment by nodchip** [comment]
https://github.com/nodchip/Stockfish/commit/35f04aaf24d05ec7b71c2cc1710d00642aaf35ec (2020-08-11) vs https://github.com/nodchip/Stockfish/commit/36092b855a5e2bcfb587a36e2055ea068e4bd8e5 (2020-07-19)
https://tests.stockfishchess.org/tests/view/5f5e0d2861bdd7a0007e76fa
ELO: -6.79 +-1.7 (95%) LOS: 0.0%
Total: 60000 W: 11291 L: 12464 D: 36245
Ptnml(0-2): 1254, 7452, 13560, 6681, 1053

https://github.com/nodchip/Stockfish/commit/26460805437761cbef758bbfa9cc1fd1fbc6b6ef (2020-08-15) vs https://github.com/nodchip/Stockfish/commit/36092b855a5e2bcfb587a36e2055ea068e4bd8e5 (2020-07-19)
ELO: -22.31 +-1.7 (95%) LOS: 0.0%
Total: 60000 W: 9698 L: 13546 D: 36756
Ptnml(0-2): 1490, 8182, 13759, 5824, 745

https://github.com/nodchip/Stockfish/commit/17d2b5bf1747e2be281866bf1e623b3bb3a4a99f (2020-08-21) vs https://github.com/nodchip/Stockfish/commit/36092b855a5e2bcfb587a36e2055ea068e4bd8e5 (2020-07-19)
ELO: -20.66 +-1.7 (95%) LOS: 0.0%
Total: 60000 W: 9809 L: 13373 D: 36818
Ptnml(0-2): 1469, 8147, 13658, 5931, 795

These show that there is regression between 2020-08-11 and 2020-08-15.  I will train a net with https://github.com/nodchip/Stockfish/commit/69a95e431b0733651a2b1a5c84d8526037ac9b04 (2020-08-15).

**Comment by nodchip** [comment]
The third target is https://github.com/nodchip/Stockfish/commit/69a95e431b0733651a2b1a5c84d8526037ac9b04 (2020-08-14).  I trained a net with the following command.
```
uci
setoption name SkipLoadingEval value true
setoption name Use NNUE value true
setoption name Threads value 16
setoption name EvalSaveDir value F:\stockfish\eval\2020-08-14.69a95e4
isready
learn targetdir F:\stockfish\training_data\2020-09-12 loop 100 batchsize 1000000 use_draw_in_training 1 use_draw_in_validation 1 eta 1 lambda 1 eval_limit 32000 nn_batch_size 1000 newbob_decay 0.5 eval_save_interval 100000000 loss_output_interval 1000000 mirror_percentage 0 validation_set_file_name F:\stockfish\validation_data\2020-09-12\generated_kifu.bin
quit
```

The training result is below.
![image 2020-09-19-10-23-45](https://user-images.githubusercontent.com/685625/93656361-b34c0a00-fa64-11ea-8fee-d3e70a0bd06a.png)

I submitted a test to fishtest.  https://tests.stockfishchess.org/tests/view/5f65605cbb0cae038ca8f5a5

**Comment by nodchip** [comment]
Also the fourth target https://github.com/nodchip/Stockfish/commit/79654ac5095af6f063a4d0f73b3621be1b8ec20f (2020-08-15) and the fifth target https://github.com/nodchip/Stockfish/commit/44a54b63f1ef637a2d35c75b7db2a6559fb34208 (2020-08-12) are trained.

The learn command for https://github.com/nodchip/Stockfish/commit/79654ac5095af6f063a4d0f73b3621be1b8ec20f (2020-08-15) is below.
```
uci
setoption name SkipLoadingEval value true
setoption name Use NNUE value true
setoption name Threads value 16
setoption name EvalSaveDir value F:\stockfish\eval\2020-08-15.79654ac
isready
learn targetdir F:\stockfish\training_data\2020-09-12 loop 100 batchsize 1000000 use_draw_in_training 1 use_draw_in_validation 1 eta 1 lambda 1 eval_limit 32000 nn_batch_size 1000 newbob_decay 0.5 eval_save_interval 100000000 loss_output_interval 1000000 mirror_percentage 0 validation_set_file_name F:\stockfish\validation_data\2020-09-12\generated_kifu.bin
quit
```

The learn command for https://github.com/nodchip/Stockfish/commit/44a54b63f1ef637a2d35c75b7db2a6559fb34208 (2020-08-12).
```
uci
setoption name SkipLoadingEval value true
setoption name Use NNUE value true
setoption name Threads value 16
setoption name EvalSaveDir value F:\stockfish\eval\2020-08-12.44a54b6
isready
learn targetdir F:\stockfish\training_data\2020-09-12 loop 100 batchsize 1000000 use_draw_in_training 1 use_draw_in_validation 1 eta 1 lambda 1 eval_limit 32000 nn_batch_size 1000 newbob_decay 0.5 eval_save_interval 100000000 loss_output_interval 1000000 mirror_percentage 0 validation_set_file_name F:\stockfish\validation_data\2020-09-12\generated_kifu.bin
quit
```

I submitted new tests,  https://tests.stockfishchess.org/tests/view/5f66ef690a78bb4d4adeda1f and https://tests.stockfishchess.org/tests/view/5f66f0730a78bb4d4adeda21.

**Comment by nodchip** [comment]
https://github.com/nodchip/Stockfish/commit/35f04aaf24d05ec7b71c2cc1710d00642aaf35ec (2020-08-11) vs https://github.com/nodchip/Stockfish/commit/36092b855a5e2bcfb587a36e2055ea068e4bd8e5 (2020-07-19)
https://tests.stockfishchess.org/tests/view/5f5e0d2861bdd7a0007e76fa
ELO: -6.79 +-1.7 (95%) LOS: 0.0%
Total: 60000 W: 11291 L: 12464 D: 36245
Ptnml(0-2): 1254, 7452, 13560, 6681, 1053

https://github.com/nodchip/Stockfish/commit/69a95e431b0733651a2b1a5c84d8526037ac9b04 (2020-08-15) vs https://github.com/nodchip/Stockfish/commit/36092b855a5e2bcfb587a36e2055ea068e4bd8e5 (2020-07-19)
https://tests.stockfishchess.org/tests/view/5f65605cbb0cae038ca8f5a5
ELO: -13.73 +-1.7 (95%) LOS: 0.0%
Total: 60000 W: 10222 L: 12592 D: 37186
Ptnml(0-2): 1293, 7656, 14005, 6220, 826

https://github.com/nodchip/Stockfish/commit/26460805437761cbef758bbfa9cc1fd1fbc6b6ef (2020-08-15) vs https://github.com/nodchip/Stockfish/commit/36092b855a5e2bcfb587a36e2055ea068e4bd8e5 (2020-07-19)
ELO: -22.31 +-1.7 (95%) LOS: 0.0%
Total: 60000 W: 9698 L: 13546 D: 36756
Ptnml(0-2): 1490, 8182, 13759, 5824, 745

https://github.com/nodchip/Stockfish/commit/17d2b5bf1747e2be281866bf1e623b3bb3a4a99f (2020-08-21) vs https://github.com/nodchip/Stockfish/commit/36092b855a5e2bcfb587a36e2055ea068e4bd8e5 (2020-07-19)
ELO: -20.66 +-1.7 (95%) LOS: 0.0%
Total: 60000 W: 9809 L: 13373 D: 36818
Ptnml(0-2): 1469, 8147, 13658, 5931, 795

I'm waiting for the results of https://tests.stockfishchess.org/tests/view/5f66f0730a78bb4d4adeda21 and https://tests.stockfishchess.org/tests/view/5f66ef690a78bb4d4adeda1f.

**Comment by nodchip** [comment]
https://github.com/nodchip/Stockfish/commit/35f04aaf24d05ec7b71c2cc1710d00642aaf35ec (2020-08-11) vs https://github.com/nodchip/Stockfish/commit/36092b855a5e2bcfb587a36e2055ea068e4bd8e5 (2020-07-19)
https://tests.stockfishchess.org/tests/view/5f5e0d2861bdd7a0007e76fa
ELO: -6.79 +-1.7 (95%) LOS: 0.0%
Total: 60000 W: 11291 L: 12464 D: 36245
Ptnml(0-2): 1254, 7452, 13560, 6681, 1053

https://github.com/nodchip/Stockfish/commit/44a54b63f1ef637a2d35c75b7db2a6559fb34208 (2020-08-12) vs https://github.com/nodchip/Stockfish/commit/36092b855a5e2bcfb587a36e2055ea068e4bd8e5 (2020-07-19)
ELO: -21.17 +-1.7 (95%) LOS: 0.0%
Total: 60000 W: 9638 L: 13290 D: 37072
Ptnml(0-2): 1428, 8216, 13690, 5912, 754

https://github.com/nodchip/Stockfish/commit/69a95e431b0733651a2b1a5c84d8526037ac9b04 (2020-08-15) vs https://github.com/nodchip/Stockfish/commit/36092b855a5e2bcfb587a36e2055ea068e4bd8e5 (2020-07-19)
https://tests.stockfishchess.org/tests/view/5f65605cbb0cae038ca8f5a5
ELO: -13.73 +-1.7 (95%) LOS: 0.0%
Total: 60000 W: 10222 L: 12592 D: 37186
Ptnml(0-2): 1293, 7656, 14005, 6220, 826

https://github.com/nodchip/Stockfish/commit/79654ac5095af6f063a4d0f73b3621be1b8ec20f (2020-08-15) vs https://github.com/nodchip/Stockfish/commit/36092b855a5e2bcfb587a36e2055ea068e4bd8e5 (2020-07-19)
ELO: -10.86 +-1.7 (95%) LOS: 0.0%
Total: 60000 W: 10697 L: 12571 D: 36732
Ptnml(0-2): 1290, 7622, 13675, 6498, 915

https://github.com/nodchip/Stockfish/commit/26460805437761cbef758bbfa9cc1fd1fbc6b6ef (2020-08-15) vs https://github.com/nodchip/Stockfish/commit/36092b855a5e2bcfb587a36e2055ea068e4bd8e5 (2020-07-19)
ELO: -22.31 +-1.7 (95%) LOS: 0.0%
Total: 60000 W: 9698 L: 13546 D: 36756
Ptnml(0-2): 1490, 8182, 13759, 5824, 745

https://github.com/nodchip/Stockfish/commit/17d2b5bf1747e2be281866bf1e623b3bb3a4a99f (2020-08-21) vs https://github.com/nodchip/Stockfish/commit/36092b855a5e2bcfb587a36e2055ea068e4bd8e5 (2020-07-19)
ELO: -20.66 +-1.7 (95%) LOS: 0.0%
Total: 60000 W: 9809 L: 13373 D: 36818
Ptnml(0-2): 1469, 8147, 13658, 5931, 795

Elo change between https://github.com/nodchip/Stockfish/commit/35f04aaf24d05ec7b71c2cc1710d00642aaf35ec (2020-08-11) and https://github.com/nodchip/Stockfish/commit/44a54b63f1ef637a2d35c75b7db2a6559fb34208 (2020-08-12) was -14.38.  https://github.com/nodchip/Stockfish/commit/44a54b63f1ef637a2d35c75b7db2a6559fb34208 (2020-08-12) is "Don't allow LMP on PvNodes".  This was disabled in https://github.com/nodchip/Stockfish/commit/69a95e431b0733651a2b1a5c84d8526037ac9b04 (2020-08-15). The Elo change between https://github.com/nodchip/Stockfish/commit/35f04aaf24d05ec7b71c2cc1710d00642aaf35ec (2020-08-11) and  https://github.com/nodchip/Stockfish/commit/69a95e431b0733651a2b1a5c84d8526037ac9b04 (2020-08-15) is -6.94.  I'm not sure why Elo didn't back to https://github.com/nodchip/Stockfish/commit/35f04aaf24d05ec7b71c2cc1710d00642aaf35ec (2020-08-11).  This was changed in https://github.com/nodchip/Stockfish/commit/30a1bc4c64e0cf41269c34868b457ed6b4b5acb5 again.  We could think that this is fixed.

The previous commits of https://github.com/nodchip/Stockfish/commit/26460805437761cbef758bbfa9cc1fd1fbc6b6ef (2020-08-15) were https://github.com/nodchip/Stockfish/commit/79654ac5095af6f063a4d0f73b3621be1b8ec20f (2020-08-15) and https://github.com/nodchip/Stockfish/commit/69a95e431b0733651a2b1a5c84d8526037ac9b04 (2020-08-15).  The Elo of https://github.com/nodchip/Stockfish/commit/26460805437761cbef758bbfa9cc1fd1fbc6b6ef (2020-08-15) was decreased from https://github.com/nodchip/Stockfish/commit/79654ac5095af6f063a4d0f73b3621be1b8ec20f (2020-08-15) and https://github.com/nodchip/Stockfish/commit/69a95e431b0733651a2b1a5c84d8526037ac9b04 (2020-08-15) even though https://github.com/nodchip/Stockfish/commit/26460805437761cbef758bbfa9cc1fd1fbc6b6ef (2020-08-15) is a merge commit.  I'm not sure why this happen.

Next, I will investigate regression between https://github.com/nodchip/Stockfish/commit/17d2b5bf1747e2be281866bf1e623b3bb3a4a99f (2020-08-21) and https://github.com/nodchip/Stockfish/commit/bc90567e0933a49f8c1911eba45ec6743a37c1ec (2020-08-30).  Also, I will check the difference between EnableTranspositionTable=true and EnableTranspositionTable=false.

**Comment by Sopel97** [comment]
https://pastebin.com/NFefgHPY
This suggests that something happened between 5637996 and 9f2f316

**Comment by nodchip** [comment]
Thank you for the information.  The changes between https://github.com/nodchip/Stockfish/commit/5637996f79566a2d720ff3eb9236c361f7c22998 and https://github.com/nodchip/Stockfish/commit/9f2f31632cbb9fc617e7044aebbfb0f2ca87c7ab was to merge the official stockfish master.  In the official stockfish master, EvalList was removed.  I fixed the compile errors about EvalList in https://github.com/nodchip/Stockfish/commit/f7bc4e6e45788b61517d5a669ca6e6d75d1b0d17.  I might have introduced bugs in that commit.  I will check it.

**Comment by nodchip** [comment]
I guess that https://github.com/nodchip/Stockfish/commit/f7bc4e6e45788b61517d5a669ca6e6d75d1b0d17#diff-67566ffb5da0927bcd078ba588fb8f4a, https://github.com/nodchip/Stockfish/commit/f7bc4e6e45788b61517d5a669ca6e6d75d1b0d17#diff-752f679a3150800587a62d5458965849 or https://github.com/nodchip/Stockfish/commit/f7bc4e6e45788b61517d5a669ca6e6d75d1b0d17#diff-42ae6f78b77f4ed21966fc01c9f074fa may have bugs.

**Comment by nodchip** [comment]
I disabled those code by commenting out source code in https://github.com/nodchip/Stockfish/blob/master/src/nnue/trainer/features/factorizer_half_kp.h, and compared the numbers of the observed features between https://github.com/nodchip/Stockfish/commit/5637996f79566a2d720ff3eb9236c361f7c22998 and https://github.com/nodchip/Stockfish/commit/2931463d3a8b2ea86ac223842dc775fb0ab68de6.

https://github.com/nodchip/Stockfish/commit/5637996f79566a2d720ff3eb9236c361f7c22998 -> 35622
https://github.com/nodchip/Stockfish/commit/2931463d3a8b2ea86ac223842dc775fb0ab68de6 -> 36265

This result shows that the changes in the following source code between https://github.com/nodchip/Stockfish/commit/5637996f79566a2d720ff3eb9236c361f7c22998 and https://github.com/nodchip/Stockfish/commit/2931463d3a8b2ea86ac223842dc775fb0ab68de6 did not change the number of the observed features.

- https://github.com/nodchip/Stockfish/blob/master/src/nnue/features/half_relative_kp.cpp
- https://github.com/nodchip/Stockfish/blob/master/src/nnue/features/half_relative_kp.h
- https://github.com/nodchip/Stockfish/blob/master/src/nnue/features/k.cpp
- https://github.com/nodchip/Stockfish/blob/master/src/nnue/features/k.h
- https://github.com/nodchip/Stockfish/blob/master/src/nnue/features/p.cpp
- https://github.com/nodchip/Stockfish/blob/master/src/nnue/features/p.h

But I found suspicious code in https://github.com/nodchip/Stockfish/blob/master/src/nnue/features/k.cpp.

```
IndexType K::MakeIndex(Color perspective, Square s, Color king_color) {
  return IndexType(orient(perspective, s) + bool(perspective ^ king_color) * 64);
}
```

This code returns the index of the feature against a given perspective, a king's square and the king's color.  In https://github.com/nodchip/Stockfish/commit/5637996f79566a2d720ff3eb9236c361f7c22998, the index of the white's king is between 0 and 63, and the index of the black's king is between 64 and 127.  But, in https://github.com/nodchip/Stockfish/commit/2931463d3a8b2ea86ac223842dc775fb0ab68de6, the index of white's king and black's king is inversed if the perspective is black.  I fixed this bug, and checked the number of the observed features.  But the number was not changed.  Though it is still suspicious.  I will train a net with this fix, and compare the Elo.

**Comment by Sopel97** [comment]
maybe we should forgo this and try merge with noobpwnftw/trainer as it's supposed to not have any issues?

**Comment by nodchip** [comment]
It's an option.  I will train a net with noobpwnftw/trainer, and compare the Elo with 2020-07-19 after the experiment above is done.
