### ISSUE TITLE
Bugs in castling right feature encoding.

### ISSUE THREAD

**Issue by Sopel97** [nodchip/Stockfish#159]
1. `i << 1` instead of `1 << i`
https://github.com/nodchip/Stockfish/blob/master/src/nnue/features/castling_right.cpp#L30
https://github.com/nodchip/Stockfish/blob/master/src/nnue/features/castling_right.cpp#L58
https://github.com/nodchip/Stockfish/blob/master/src/nnue/features/castling_right.cpp#L59

**Comment by nodchip** [comment]
It should be right.  Could you please send a pull request?
