### ISSUE TITLE
Compiling with profile-build is broken

### ISSUE THREAD

**Issue by hero2017** [nodchip/Stockfish#172]
Using gcc 10.2 I can successfully compile with make build in Ubuntu 20.04 but make profile-build fails as follows:

Step 2/4. Running benchmark for pgo-build ...
./stockfish bench > /dev/null

Position: 1/47 (rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1)

Position: 2/47 (r3k2r/p1ppqpb1/bn2pnp1/3PN3/1p2P3/2N2Q1p/PPPBBPPP/R3K2R w KQkq - 0 10)
make: *** [Makefile:758: profile-build] Error 1

**Comment by nodchip** [comment]
It looks that the net is not loaded correctly.  Could you please remove all the net files in the same folder, and try again?

**Comment by hero2017** [comment]
Yes you're right. My bad. I forgot to cp the net to the src folder. Sorry to have wasted your time.
