### ISSUE TITLE
Wrong fullmove in fen in conversion to plain.

### ISSUE THREAD

**Issue by Sopel97** [nodchip/Stockfish#252]
Should be `return m_ply / 2 + 1;` instead of `return (m_ply + 1) / 2;` I think, in `Position::fullMove()` in `nnue_data_binpack_format.h` around line 4500. `setFullMove` possibly also requires changing.

**Comment by vondele** [comment]
Stockfish has this in Position::fen()
st->rule50 << " " << 1 + (gamePly - (sideToMove == BLACK)) / 2;

**Comment by Sopel97** [comment]
ply is adjusted at assignment for sign to move, so that's the bit with sidetomove out. What's left is indeed gamePly/2+1
