### ISSUE TITLE
Loading the net and doing some stuff after 'isready'.

### ISSUE THREAD

**Issue by joergoster** [nodchip/Stockfish#28]
This is somewhat abusing the UCI protocol.

The command 'isready' is meant for syncronizing the GUI and the engine.
After an 'isready', all the engine must do is to answer with 'readyok'. 'isready' is usually sent after one or more 'setoption' commands, after a 'ucinewgame' (mandatory), and may also be sent whenever the GUI wants to know whether the engine is still 'alive'.

A better solution would be to load the NN after 'ucinewgame' command, where we also initialize some search stuff with Search::clear(). This will also allow to do profile builds.

**Comment by nodchip** [comment]
Eval is loaded in "isready" so that we can change the eval folder with setoption.

If we want to use profile builds, another option will be to change setup_benchmark() to add "isready" to the command list, and process "isready" in the bench().  I think that we can use bench command without "isready" command, and we can also use profile builds.

**Comment by joergoster** [comment]
Yeah, but that would mean we are abusing the protocol even more. I don't want to do this. ;-)

I think I will go with a separate function to only load the eval after 'ucinewgame', and still keep is_ready() function as is which is needed by learner.cpp and multi_think.cpp, as far as I understand it.

**Comment by ianfab** [comment]
IMO, the handling of tablebases is a very similar problem and indicates how official SF authors would perhaps approach this. Therefore, to me loading the eval on `ucinewgame` as well as on `setoption` of the evalDir path would be consistent. I do not know how this fits with the training part though.

**Comment by nodchip** [comment]
I confirmed that a tablebase is initialized in ucinewgame.  I think that it is reasonable to load eval file in ucinewgame to make consistent between eval file and tablebase.

**Comment by joergoster** [comment]
Here https://github.com/joergoster/Stockfish/commit/7527ba7f37a1d33de7fcb86d9fba98afb4c78ab1 I tried to address this.

**Main changes:**

- is_ready() renamed to init_nnue() and simplified, all calls to is_ready() replaced accordingly. There is no need to send empty lines which will at best be simply ignored. TT.resize() is automatically executed after a "setoption name Hash value xxx" anyway, and Search::clear() is done after "ucinewgame".
- The net will now be loaded after "ucinewgame", if necessary, and always after changing `EvalDir`.
- init_nnue() now included in both, the bench command and in the main UCI loop after receiving "ucinewgame" command. This will allow to do profile-builds with the NNUE net loaded.

Comments/Suggestions welcome.

**Comment by nodchip** [comment]
@joergoster 
I checked the changes. They looks reasonable.  Could you send a pull request?

**Comment by joergoster** [comment]
@nodchip Sure. Thank you for reviewing. Closing this issue.
