### ISSUE TITLE
Would be nice if issue is labelled bug if it is a bug

### ISSUE THREAD

**Issue by fsmosca** [nodchip/Stockfish#314]
It makes you interested about the issue and would try to fix it.

**Comment by Sopel97** [comment]
Currently only @nodchip is a maintainer and no one else is allowed to change labels, but he's not active here. It would definitely be better to have someone involved in the project with these specific rights.

**Comment by nodchip** [comment]
@Sopel97 Could you please enumerate some contributors?  I will give them permissions.

**Comment by Sopel97** [comment]
me, @vondele (current maintainer of stockfish), @NightlyKing (Additional Pylon)

**Comment by nodchip** [comment]
I sent invitations to @Sopel97, @vondele and @NightlyKing as collaborators.
