### ISSUE TITLE
Allow "gensfen" to use fixed nodes

### ISSUE THREAD

**Issue by NightlyKing** [nodchip/Stockfish#32]
So far gensfen only allows us to use a fixed depth which results in very weak endgames compared to the early and midgame. 2 million nodes (which is about 1 second on 1 core) reaches about depth 20 from the starting position and in endgames over 40 at times. If we limit by depth we cut a lot of nodes because in the endgame a lot of lines can be pruned and thus we reach higher depth much more quickly.
Overall, using nodes instead of depth shouldn't slow us down since SF gains a lot of speed in the endgame as well.

**Comment by nodchip** [comment]
Thank you for suggesting.  I can implement the feature.  But I'm very busy until this weekend.  I will work on it in the next week.

**Comment by nodchip** [comment]
This feature is implemented in https://github.com/nodchip/Stockfish/releases/tag/stockfish-nnue-2020-07-06.  I will close this issue.
