### ISSUE TITLE
Failure to load nnue trained by https://github.com/glinscott/nnue-pytorch

### ISSUE THREAD

**Issue by arashesfahany** [nodchip/Stockfish#329]
The UCI cannot load an nnue which was trained with https://github.com/glinscott/nnue-pytorch.

The error:
"info string ERROR: If the UCI option "Use NNUE" is set to true, network evaluation parameters compatible with the engine must be available.
info string ERROR: The option is set to true, but the network file t1.nnue was not loaded successfully.
info string ERROR: The UCI option EvalFile might need to specify the full path, including the directory name, to the network file.
info string ERROR: The default net can be downloaded from: https://tests.stockfishchess.org/api/nn/nn-c3ca321c51c9.nnue
info string ERROR: The engine will be terminated now."

**Comment by vondele** [comment]
this is expected, the nnue-pytorch repo is intended to be used with https://github.com/official-stockfish/Stockfish. This is where development is currently taking place.
