### ISSUE TITLE
Final net not being saved

### ISSUE THREAD

**Issue by joergoster** [nodchip/Stockfish#48]
There are reports at discord that the best net after the training has finished does not get saved into the final folder.

In bool LearnerThink::save() in learner.cpp, we pass the directory with the best NN for restoring before saving into the final folder.
```
					cout << "restoring parameters from " << best_nn_directory << endl;
					Eval::NNUE::RestoreParameters(best_nn_directory);
```

However, it looks like this string doesn't get used in RestoreParameters() in evaluate_nnue_learner.cpp.
```
// Reread the evaluation function parameters for learning from the file
void RestoreParameters(const std::string& dir_name) {
  const std::string file_name = NNUE::fileName;
  std::ifstream stream(file_name, std::ios::binary);
  bool result = ReadParameters(stream);
  assert(result);

  SendMessages({{"reset"}});
}
```

Do we need to change `file_name` into
`  const std::string file_name = Path::Combine(dir_name, NNUE::savedfileName);` ?

This probably needs to be tested before getting applied, though.

**Comment by nodchip** [comment]
Yes.  I agree with you.  Could you please send a pull request?

**Comment by joergoster** [comment]
I did a quick testrun with a small net.
Restoring parameters when a net gets rejected still seems to work.

> save_eval() start. folder = evalsave/5
> save_eval() finished. folder = evalsave/5
> loss: 0.352335 >= best (0.352268), rejected
> restoring parameters from evalsave/4
> reducing learning rate scale from 0.5 to 0.25 (1 more trials)

And also the final restoring of the best net and saving into final folder looks ok now.

> save_eval() start. folder = evalsave/6
> save_eval() finished. folder = evalsave/6
> loss: 0.352853 >= best (0.352268), rejected
> restoring parameters from evalsave/4
> converged

> 
> finalize..all threads are joined.
> info string NNUE net/nn.bin found & loaded
> Check Sum = 0
> save_eval() start. folder = evalsave/final
> save_eval() finished. folder = evalsave/final
