### ISSUE TITLE
Two kings on same Square

### ISSUE THREAD

**Issue by jjoshua2** [nodchip/Stockfish#53]
Data generated from native stockfish from this repository.

Board looks like:
r . . . r . k .
p p . . . p . p
. . p . n . p .
. . . . . . . n
P . . P P . . P
. b . . . . P .
P B . . . P . .
. . . R R . K . 
Result 0.0
Kings on 6 and 62.

Next position saved both kings are on square 63 and everything crashes, for next 40 ply.

Next position I can parse is:
. . B . . . . k
. . . . . . . .
. . . . . . p .
. . . . . p . .
P R . . . . n .
. . . . . . P .
r . . . . . . .
. . . . . . . K 
Result 0.5

I guess this must be a different game because result is different? But it didn't start at beginning but here so maybe this is another bug?

Then many many positions are fine and later on in same file I  have both kings on square 63 again...

I have generated many other files successfully with no issues, but this one has a lot of problems...

**Comment by nodchip** [comment]
Sorry for late response.  Could you please share the training data?  I will check it.

**Comment by jjoshua2** [comment]
This one has many bad ones https://mega.nz/file/2MJWnKTB#siLu5-5qsF4ULEr7ezgL-5_4Q2b9pkTZab2NwM48BAQ

**Comment by jjoshua2** [comment]
This one has a bad fen about 98/100M https://mega.nz/file/qUJQQQoa#ixqNamV0KEpDZ6V7xEuVume76jfrBiiWLLWGdF-I_nc

**Comment by nodchip** [comment]
Thank you for sharing.  I will check it later.

**Comment by Sopel97** [comment]
Is this solved? I'm not aware of any other reports for this bug.

**Comment by nodchip** [comment]
I have not checked this bug.  I also don't hear similar reports for this bug.  We could close this bug.
