### ISSUE TITLE
Crash under linux

### ISSUE THREAD

**Issue by maximiliano1956** [nodchip/Stockfish#54]
I launch Stockfish in a terminal and BEFORE it loads the network (which happens for example with the command "ucinewgame")
i do commands like "go infinite" or "go nodes 100" :  the program immediately crashes.
We should put a check on some commands that the network has been loaded.

**Comment by nodchip** [comment]
Hi @maximiliano1956 ,
Could you please ask questions in the #sf-nnue-help channel in the  unofficial Stockfish Discord server?
Here is an invitation link. https://discord.gg/ZzJwPv3

**Comment by nodchip** [comment]
I will close this issue for now.  Could you please reopen or open a new issue if the problem still exists?
