### ISSUE TITLE
Without skiploading, evalsave/final/nn.bin and eval/nn.bin are identical

### ISSUE THREAD

**Issue by dkappe** [nodchip/Stockfish#56]
Looks like the uci options get restored before the final save, causing the net to be reloaded, which is then saved as the final. On linux, setting skiploading to true causes a segfault on final save, which may be related.

**Comment by nodchip** [comment]
Could you please ask in the #sf-nnue-help channel in the unofficial Stockfish Discord server?  Here is an invitation link. https://discord.gg/ZzJwPv3

**Comment by MRMikaelJ** [comment]
The bug as I understand it is that the readme states: 
"After training is finished, your new net should be located in the "**final**" folder under the "evalsave" directory. You should test this new network against the older network to see if there are any improvements."

This is might not be true. After finalizing training the original network from **before** training was started is reloaded and saved in **final**. To find the actual result of the "reinforcement learning" you must look for which evalsave was last accepted and take that (**evalsave/5**).

**Comment by joergoster** [comment]
Theoretically, this [commit](https://github.com/nodchip/Stockfish/commit/e29499ee4b99174570fc49ac918f1dbd5bc22660) should have fixed it.
Do you still experience the same issue?

However, if `save_only_once` is true, we do not save into a final folder. Probably not what we want ...

**Comment by Sopel97** [comment]
Is this still an issue? Looking at the code it seems to be fixed.

**Comment by nodchip** [comment]
@dkappe Could you please check if this bug still exists?

**Comment by Sopel97** [comment]
@nodchip this is not an issue anymore, please close
