### ISSUE TITLE
Is a support of arm 8 cpu on android possible?

### ISSUE THREAD

**Issue by spasski** [nodchip/Stockfish#58]
We are living in a world of modern devices.

Who compile SF-NNUE for this world?

**Comment by nodchip** [comment]
I'm sorry but I don't have any ideas.  Could you please ask in the #general-sf-nnue channel in the unofficial Stockfish Discord server? Here is an invitation link. https://discord.gg/ZzJwPv3

**Comment by nodchip** [comment]
Compilation for ARMv8 is supported in the official Stockfish master branch.
https://github.com/official-stockfish/Stockfish/commit/81490ebc75fdc9c183a4cdb7826f38395400c172
https://github.com/official-stockfish/Stockfish/commit/c402fe7d26c910ea43bd538ef3c07b25fed3ba67

And I saw that someone compiled binaries for ARM in the unofficial Stockfish Discord server.

I will close this issue.
