### ISSUE TITLE
Wrong release comment

### ISSUE THREAD

**Issue by Silver-Fang** [nodchip/Stockfish#60]
The 0719 release says to find a network on #sf-nnue-dev channel, but the channel doesn't exist.

**Comment by nodchip** [comment]
Thank you for asking question.  The channel name was changed to #sf-nnue-help.  I updated the description.

**Comment by Silver-Fang** [comment]
> Thank you for asking question. The channel name was changed to #sf-nnue-help. I updated the description.

#sf-nnue-help channel disappeared 😓. These channels are so volatile.

**Comment by nodchip** [comment]
I removed the channel name in the release description. 😅
