### ISSUE TITLE
Load a pgn to generate data with those lines...

### ISSUE THREAD

**Issue by glennsamuel32** [nodchip/Stockfish#61]
Could we have the option to load a pgn (maybe 5 moves per game) so that we can direct the  "gensfen"  command to generate data using those lines ?
This would speed up the learning process and not waste time with useless lines.

**Comment by nodchip** [comment]
Thank you for the feature request.
Could you please ask someone in #general-sf-nnue in the unofficial Stockfish Discord server?  (https://discord.gg/ZzJwPv3)  I will merge a pull request once it is sent to this repository.

**Comment by Sopel97** [comment]
This can be achieved by .epd books using the `books` option for `gensfen`. Adding support for PGN into stockfish is too much to ask for right now. I think this can be closed.
