### ISSUE TITLE
Chessbase and Fritz

### ISSUE THREAD

**Issue by MRMikaelJ** [nodchip/Stockfish#65]
It has been reported at the default binaries doesn't work right out of the box for Chessbase and Fritz. A special compile was made for fritz for a earlier release  https://discordapp.com/channels/435943710472011776/733547343319924808/733726540231344218.

Do not know if this will be relevant for the nnue player made by the stockfish right now.

**Comment by nodchip** [comment]
Thank you for reporting an issue.
I and some people from Stockfish community are working on integrating NNUE in the official branch of Stockfish.  I'm stopping modifying my repository to avoid interferes with those works.  Once the part of NNUE is integrated in the official branch, we could work on the issue.

**Comment by JavaMast** [comment]
Need to make shorter internal name
https://github.com/nodchip/Stockfish/blob/master/src/misc.cpp#L143
That's all

![Screenshot_734](https://user-images.githubusercontent.com/42765009/88221273-e6dd0480-cc6c-11ea-9c21-22f14eea0fe6.png)

**Comment by nodchip** [comment]
NNUE has been merged into the official Stockfish repository.
https://github.com/official-stockfish/Stockfish/commit/84f3e867903f62480c33243dd0ecbffd342796fc

Could you please ask about this issue in the official Stockfish repository?  I will close this issue.
