### ISSUE TITLE
Gensfen TB bug

### ISSUE THREAD

**Issue by sergiovieri** [nodchip/Stockfish#67]
When doing `gensfen` from `nnue-learn`, search does not use TB even though it is supplied.

It is caused by `TB::Cardinality` to be unset, which defaults to 0.

A temporary fix is to call `Tablebases::rank_root_move()` from inside `Learner::search()`, which sets `TB::Cardinality` to the correct value. I'm not sure if this is the way to go.

**Comment by nodchip** [comment]
Thank you for reporting.  linox has worked on this issue.  I will take a look his or her source code, and merge as needed.
[Stockfish-master.zip](https://github.com/nodchip/Stockfish/files/5010190/Stockfish-master.zip)

**Comment by nodchip** [comment]
This issue was fixed in the release stockfish-nnue-2020-08-11.
https://github.com/nodchip/Stockfish/releases/tag/stockfish-nnue-2020-08-11
I will close this issue.
