### ISSUE TITLE
Training generator generates same training data each run (Not random)

### ISSUE THREAD

**Issue by mbabigian** [nodchip/Stockfish#68]
The PRNG is seeded with a constant.  This causes the .bin files to be identical at the same depth for consecutive runs.  Many like Sergio are generating data on multiple machines.  You can verify this problem by setting Threads to 1 so that Stockfish is deterministic.  Generate training bin file and rename.  Repeat and binary file compare the two runs.  They will be identical.

The fix is to modify multi_think.h about line 19 with

```
    std::random_device seed_it;
    MultiThink() : prng(seed_it()) //21120903

```
There is a second constant seed in nnue_test_command.cpp at around line 32 that should be modified the same way.  Both jjosh and Sergio are implementing this change (Sergio is generating on multiple machines).  Nets created prior to this change are likely over training the same positions.

Regards,
Mike

**Comment by nodchip** [comment]
Thank you for reporting.
I will check if after the part of NNUE is integrated into the original Stockfish.

**Comment by mbabigian** [comment]
You are most welcome.  One of the SF devs didn't think there was an issue with you continuing to patch, but up to you.  Most of us are just updating this small stuff in the mean time.  Great work by the way.  I think chess engines are going to make major Elo gains in the next 12 to 24 months.  Thank you!

**Comment by nodchip** [comment]
This issue was fixed in the release stockfish-nnue-2020-08-11.
https://github.com/nodchip/Stockfish/releases/tag/stockfish-nnue-2020-08-11
I will close this issue.
