### ISSUE TITLE
convert_bin made crash learn exe

### ISSUE THREAD

**Issue by deedstacktyk** [nodchip/Stockfish#72]
if i try to convert my plain text file into a training bin file with this command :

stockfish.bmi2.halfkp_256x2-32-32.nnue-learn.2020-07-19.exe
Stockfish+NNUE 190720 64 BMI2 by T. Romstad, M. Costalba, J. Kiiski, G. Linscott, H. Noda, Y. Nasu, M. Isozaki
learn convert_bin output_file_name reinforcing.bin reinforcing.txt
learn command , learn from reinforcing.txt ,
base dir        :
target dir      :
Error! ./eval/nn.bin not found or wrong format
convert_bin..
convert reinforcing.txt ...

=> the exe crashes and the renforcing.bin file weigths 0 bytes...

=> but if i prepare things with the conversion of a little sample of pre-generated positions (by gensfen) and only after that i retry to convert my plain text file into a training bin file, it works :

stockfish.bmi2.halfkp_256x2-32-32.nnue-learn.2020-07-19.exe
Stockfish+NNUE 190720 64 BMI2 by T. Romstad, M. Costalba, J. Kiiski, G. Linscott, H. Noda, Y. Nasu, M. Isozaki
learn convert_bin output_file_name init.bin init.txt
learn command , learn from init.txt ,
base dir        :
target dir      :
Error! ./eval/nn.bin not found or wrong format
convert_bin..
convert init.txt ... done10 parsed 0 is filtered
all done
learn convert_bin output_file_name reinforcing.bin reinforcing.txt
learn command , learn from reinforcing.txt ,
base dir        :
target dir      :
convert_bin..
convert reinforcing.txt ... done1427786 parsed 0 is filtered
all done

=> and my training.bin file weigths 50MB !

this bug occur on several computer here

**Comment by nodchip** [comment]
Thank you for reporting.  I will check it later.

**Comment by jjoshua2** [comment]
I've had this issue a lot. convert_bin doesn't do any error checking to make sure moves are legal for example, and training will crash if they are not. It would be nice if there was error handling to know if it was invalid fen, move, score etc, and what it was...

**Comment by deedstacktyk** [comment]
After checked the min/max values of the converted .txt file from the 100m depth8 .bin file generated with gensfen and i discovered that :
- the scores values go from -16000 to +16000 (-160.00 to +160.00) without "mat" or "#" or "+" symbols
- the ply values go from 15 to >300
- the number of pieces into fen strings goes from 3 to 32
![Image1](https://user-images.githubusercontent.com/54830918/89529940-ea849580-d7ed-11ea-9a0e-e4ea24b901f2.jpg)

I checked the same min/max values of the converted .txt file from my .pgn files and i saw some score over +/-99999 !?

**Comment by nodchip** [comment]
@tttak Do you have any ideas about this issue?

**Comment by tttak** [comment]
I think it is certainly necessary to limit scores between -32000 and +32000.

I think it's possible to add an option to exclude illegal moves from the conversion.
UCI::to_move() returns MOVE_NONE for illegal moves, so implementation may be relatively easy as well.

It would be preferable to be able to exclude invalid fens from the conversion as well, but implementation may be a bit difficult.
In convert_bin, we're simply calling Position::set().
The comment on Position::set() says the following.

/// Position::set() initializes the position object with the given FEN string.
/// This function is not very robust - make sure that input FENs are correct,
/// this is assumed to be the responsibility of the GUI.

**Comment by jjoshua2** [comment]
Just make sure to report % of invalid for white and for black because I had
issue once were black had some issues in my conversion and it crashed
training. This would have made it easy to spot and less of an issue.

**Comment by deedstacktyk** [comment]
here i solved the problem with a pre-converted sample (from generated positions by gensfen) before converting my plain text file. Since my scores are all between -32000 / +32000 and ply > 14, as i didn't have invalid fen, now the training work.
