### ISSUE TITLE
Consider column-major storage in AffineTransform,like in FeatureTransformer

### ISSUE THREAD

**Issue by sf-x** [nodchip/Stockfish#73]
https://hxim.github.io/Stockfish-Evaluation-Guide/?p=nnue tool shows that the activations in hidden layers are also sparse (in the biggest layer, less than 1/4 in the positions I tried). Therefore, switching to column-major (possibly tiled) storage of matrix in `AffineTransform` class, like in `FeatureTransformer` (or more complicated) should be a major (yes, word play was intentional) speedup in the "non-SIMD" (really compiler-generated SIMD) case, and relatively simple to implement.
Besides, this format would permit SIMD using scalar instruction (since the entire column is mul'd by the same value).
Also possible that that means the initialization is not optimal and many "neurons" end up not affecting anything.

**Comment by nodchip** [comment]
Thank you for suggestion.  I thought that the motivation in the suggestion is to speed up in old CPUs.  I wonder how important the speed up is in the non-SIMD case.  Please correct me if I misunderstood.
I also think that it might be more important to increase the density in hidden layers.  It might increase the power of expression, and increase the elo.  I don't have any ideas about this topic for now.

**Comment by sf-x** [comment]
> Thank you for suggestion. I thought that the motivation in the suggestion is to speed up in old CPUs.

Mostly yes.
> I wonder how important the speed up is in the non-SIMD case. Please correct me if I misunderstood.

The fraction of activated neurons with present networks is so low as to potentially make this a speed-up even in the SIMD case.

**Comment by nodchip** [comment]
Thank you for the explanation.  I think that Issues in official-stockfish/Stockfish is the right place to suggest feature requests.  Could you please create an issue on official-stockfish/Stockfish?

**Comment by nodchip** [comment]
I confirmed that you have created an issue on the official Stockfish repository.  I will close this issue.
