### ISSUE TITLE
Halfmove count wraps at 63

### ISSUE THREAD

**Issue by mbabigian** [nodchip/Stockfish#75]
To reproduce import fens using "learn convert_bin" then rename the output file and reverse with "learn convert_plain"  Check the output file.  Look at fens that had a halfmove count greater than 63.  64 becomes 0, 65 becomes 1, etc.

Looks like an overflow.  

Adding this issue to document the behavior.

**Comment by nodchip** [comment]
Thank you for reporting.  I will take a look it after NNUE is integrated into the official Stockfish branch.

**Comment by gcp** [comment]
The bug is there:
https://github.com/nodchip/Stockfish/blob/master/src/extra/sfen_packer.cpp#L198

It's written as 6 bits, but the count is in halfmoves so it can go up to 100.

To keep data files compatible it will probably have to be clamped.

**Comment by Sopel97** [comment]
Okay, I'm looking at this now and trying to find a way to fix this without breaking backwards compatibility. It's unfortunate that the value of the padding byte was not standardized and different tools used different values there. The are, however, 253 spare values in the `game_result` byte. So it is possible to encode the version by using different values for `game_result`. I'll try to implement that change.
