### ISSUE TITLE
「README.md」と「Readme.md」

### ISSUE THREAD

**Issue by tttak** [nodchip/Stockfish#83]
こんばんは。
convert_binの件でPull Requestを送らせて頂こうと思っているのですが、
現在、「README.md」と「Readme.md」が存在していまして
Windows環境のgitだとうまく処理できないようです。
おそらく意図的に2つのファイルを作成されたのではないと思うのですが、
どちらか一方を削除して頂くことは可能でしょうか？

**Comment by nodchip** [comment]
いつもお世話になっております。
https://github.com/nodchip/Stockfish/commit/ee823afdad97848c6398dbbf69aa8d9629af465f
で削除させていただきました。
本issueを閉じさせていただきたいと思います。
