### ISSUE TITLE
Enable PGO optimization for both eval for profile-learn

### ISSUE THREAD

**Issue by Serianol** [nodchip/Stockfish#87]
I recently added a new makefile target: `profile-learn` that enable pgo for the gensfen command #86 and gives a nice speed up
However, it will only optimize `gensfen` for the default eval and not both
This is because the command used during pgo is `gensfen depth 3 loop 100000` and use the default eval only
Ideally one would want a compile optimized for both eval.

**Comment by Sopel97** [comment]
Stockfish uses hybrid eval by default now, so both should be covered now?

**Comment by nodchip** [comment]
If the positions used in bench command contains positions whose material values are unbalanced between white and black.  And I guess there are such positions.  We could close this bug.

**Comment by Sopel97** [comment]
I did `dbg_hit_on(false)` for classic eval and `dbg_hit_on(true)` for nnue eval. For `bench` I get `Total 2070788 Hits 589116 hit rate (%) 28`. This means that 28% of evals are nnue, the rest are classic. I think this is sufficient.

**Comment by nodchip** [comment]
Sounds great.  We could close this issue.
