### ISSUE TITLE
Towards a better training data storage format.

### ISSUE THREAD

**Issue by Sopel97** [nodchip/Stockfish#95]
There are defects in the current .bin format that cannot be addressed without breaking backwards compatibility.

For example:
https://github.com/nodchip/Stockfish/issues/75 (This is actually regarding 50-move rule)
Similarily the half-move counter wraps after 255.

This could be addressed with simple changes and a new, say, ".bin2" format. But if we're going to lengths to have a better format then we could as well improve it in other ways while we have an occasion to make breaking changes. I have created a [format](https://github.com/Sopel97/nnue_data_compress) that doesn't have the abovementioned issues and also allows for much smaller files (around 15x smaller than .bin) [provided that concerns from #91  get addressed]. Therefore I come with a proposition of including the ability to use that format for serialization and deserialization. To make this change as simple as possible I could create a header only library that provides a writer and a reader class with simple API similar to fstream and with a generic interface that can be easly called with stockfish's chess primitives. I would like to hear your thoughts on this and if I should pursue this.

I want this issue to also serve as a place to report further fundamental issues with the .bin format that cannot be addressed in a backwards compatibile way and other potential ways of improving upon it in a second iteration.

**Comment by nodchip** [comment]
I think that it is ok to break the compatibility for the old binaries if there are enough advantages.  And it is better if there are methods to convert old format to the new format.  Could you please describe about the new format, and the interface?

I think that `learn shuffle` also can be done with the new format.  The old format used fixed length format to implement `learn shuffle` easily.

**Comment by Sopel97** [comment]
> Could you please describe about the new format

```
[[nodiscard]] std::uint16_t signedToUnsigned(std::int16_t a) {
    std::uint16_t r;
    std::memcpy(&r, &a, sizeof(std::uint16_t));
    if (r & 0x8000) r ^= 0x7FFF; // flip value bits if negative
    r = (r << 1) | (r >> 15); // store sign bit at bit 0
    return r;
}
```
```
file := <block>*
block := BINP<chain>*
chain := <stem><movetext>
stem := <pos><move><score><ply_and_result><rule50> (32 bytes)
pos := https://github.com/Sopel97/nnue_data_compress/blob/master/src/chess/Position.h#L1166 (24 bytes)
move := https://github.com/Sopel97/nnue_data_compress/blob/master/src/chess/Chess.h#L1044 (2 bytes)
score := signedToUnsigned(score) (2 bytes, big endian)
ply_and_result := ply bitwise_or (signedToUnsigned(result) << 14) (2 bytes, big endian)
rule50 := rule_50_counter (2 bytes, big endian) 
    // this is a small defect from old version, 
    I didn't want to break backwards compatibility. Effectively means that there's 
    one byte left for something else in the future because rule50 always fits in one byte.

movetext := <count><move_and_score>*
count := number of plies in the movetext (2 bytes, big endian). Can be 0.
move_and_score := <encoded_move><encoded_score> (~2 bytes)
encoded_move := oof this one is complicated to explain. 
    https://github.com/Sopel97/nnue_data_compress/blob/master/src/compress_file.cpp#L827. 
    https://github.com/Sopel97/chess_pos_db/blob/master/docs/bcgn/variable_length.md

encoded_score := https://en.wikipedia.org/wiki/Variable-width_encoding 
    with block size of 4 bits + 1 bit for extension bit.
    Encoded value is signedToUnsigned(-prev_score - current_score) 
    (scores are always seen from the perspective of side to move in <pos>, that's why the '-' before prev_score)
```
-------------------------------------------------------
> and the interface

The interface would be pretty much
```
struct TrainingDataEntry {
    std::string fen;
    std::uint16_t move; // in stockfish format
    std::int16_t score;
    std::uint16_t ply;
    std::int16_t result;
};

class TrainingDataReader {
    Reader(std::string filename);
    bool hasNext();
    TrainingDataEntry next();
};

class TrainingDataWriter {
    Writer(std::string filename, bool append);
    void write(TrainingDataEntry);
};
```
---------------------------------------------------------

> I think that learn shuffle also can be done with the new format. The old format used fixed length format to implement learn shuffle easily.

Since my format doesn't have fixed length entries then shuffling becomes a potential problem. Since from what I see the shuffled entries are never persisted then using 32 byte `<stem>`s for encoding each entry and shuffling that would be sufficient. If they are persisted then the entries would need to be 34 bytes and include two zero bytes at the end (indicating that no movetext follows)

```
struct PackedTrainingDataEntryStem {
    unsigned char data[32];
};

PackedTrainingDataEntryStem pack(TrainingDataEntry);
TrainingDataEntry unpack(PackedTrainingDataEntryStem);
```

**Comment by nodchip** [comment]
Thank you for the description.  I understand the basic ideas are:
- Encode a position with bitboard (8 bytes) + piece types (4 bits * 32).
- Add moves and scores to a position with the number of moves and scores.

With your new format, the training data generator will write smaller output.  But after `learn shuffle`, the data size is 34 bytes per a position.  It is not so smaller than the current format (40 bytes).  I'm not sure if there merits with the new format.  I would like to listen other developer's opinions.

**Comment by Sopel97** [comment]
It may indeed be too much for too little gain if `learn shuffle` is a common operation. Maybe something simpler that encodes `position + move + score + ply + rule50 + result` in `24+2+2+2+1+1==32` bytes would be better for a second iteration of bin?
